### ISSUE TITLE
Token is hardcoded while it seems to be set dynamically in the app code

### ISSUE THREAD

**Issue by lobstrio** [axeleroy/commechezsoi#1]
Can you please explain how you got this token : 

```java
 public static final String SELOGER_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTZUxvZ2VyLW1vYmlsZSIsImFwcCI6IjYzZWU3MTRkLWE2MmEtNGEyNy05ZmJlLTQwYjdhMmMzMThlNCIsImlhdCI6MTUzOTQ0MjMyMCwianRpIjoiNWYzODRhNDYtZjk5MS00ODZkLWFkN2YtMmE2M2YxZTdkM2UwIiwiYXVkIjoiU2VMb2dlci1Nb2JpbGUtNi4wIn0.Qib13Y4395f_bi5Df0IhMQRvIxQZEfpf8Ac66oTfyiA";
```
That will be needed for further updates and probably for scaling the scraping.

**Comment by axeleroy** [comment]
Hello,

This token was found a year ago by inspecting packets sent by SeLoger's Android app.

I have been told that the API has been significantly changed and that they implemented certificates pinning since then, rendering my code obsolete.

Good luck!
